# Generated by Django 5.2.17 on 2026-08-27 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='fecha')),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='horas trabajadas')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='tarifa por hora')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='monto bruto')),
                ('status', models.CharField(choices=[('borrador', 'borrador'), ('liquidada', 'liquidada'), ('pagada', 'pagada')], default='borrador', max_length=20, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='pagada el')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='staff.employee', verbose_name='empleado')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidaciones_generadas', to=settings.AUTH_USER_MODEL, verbose_name='generada por')),
            ],
            options={
                'verbose_name': 'liquidación',
                'verbose_name_plural': 'liquidaciones',
                'ordering': ['-date', 'employee__user__username'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
