# Generated by Django 5.2.17 on 2026-08-26 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('tables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='teléfono')),
                ('date', models.DateField(verbose_name='fecha')),
                ('start_time', models.TimeField(verbose_name='hora de inicio')),
                ('party_size', models.PositiveSmallIntegerField(default=2, verbose_name='cantidad de personas')),
                ('status', models.CharField(choices=[('pendiente', 'pendiente'), ('confirmada', 'confirmada'), ('cancelada', 'cancelada'), ('completada', 'completada')], default='pendiente', max_length=20, verbose_name='estado')),
                ('note', models.TextField(blank=True, verbose_name='nota')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='creada por')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='customers.customer', verbose_name='cliente')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='tables.table', verbose_name='mesa')),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
