# Generated by Django 5.2.17 on 2026-08-26 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='número')),
                ('capacity', models.PositiveSmallIntegerField(default=2, verbose_name='capacidad')),
                ('zone', models.CharField(choices=[('barra', 'barra'), ('salón', 'salón'), ('terraza', 'terraza'), ('privado', 'privado')], default='salón', max_length=20, verbose_name='zona')),
                ('status', models.CharField(choices=[('libre', 'libre'), ('ocupada', 'ocupada'), ('reservada', 'reservada'), ('limpieza', 'limpieza')], default='libre', max_length=20, verbose_name='estado')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'mesa',
                'verbose_name_plural': 'mesas',
                'ordering': ['zone', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('abierta', 'abierta'), ('cerrada', 'cerrada'), ('pagada', 'pagada'), ('cancelada', 'cancelada')], default='abierta', max_length=20, verbose_name='estado')),
                ('note', models.TextField(blank=True, verbose_name='nota')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='abierta el')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='cerrada el')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('waiter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='mozo')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='tables.table', verbose_name='mesa')),
            ],
            options={
                'verbose_name': 'comanda',
                'verbose_name_plural': 'comandas',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio unitario')),
                ('status', models.CharField(choices=[('pendiente', 'pendiente'), ('entregado', 'entregado'), ('cancelado', 'cancelado')], default='pendiente', max_length=20, verbose_name='estado')),
                ('note', models.CharField(blank=True, max_length=250, verbose_name='nota')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='solicitado el')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tables.order', verbose_name='comanda')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='inventory.product', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'ítem de comanda',
                'verbose_name_plural': 'ítems de comanda',
            },
        ),
    ]
