# Generated by Django 5.2.17 on 2026-08-26 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('unit', models.CharField(choices=[('unidad', 'unidad'), ('botella', 'botella'), ('jarra', 'jarra'), ('porción', 'porción'), ('kg', 'kg'), ('l', 'l')], default='unidad', max_length=20, verbose_name='unidad')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='precio de compra')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio de venta')),
                ('stock_current', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='stock actual')),
                ('stock_min', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='stock mínimo')),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='código de barras')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.category', verbose_name='categoría')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Positiva para entradas/compras, negativa para salidas/ventas.', max_digits=10, verbose_name='cantidad')),
                ('movement_type', models.CharField(choices=[('entrada', 'entrada'), ('salida', 'salida'), ('ajuste', 'ajuste'), ('venta', 'venta'), ('compra', 'compra')], max_length=20, verbose_name='tipo de movimiento')),
                ('reference', models.CharField(blank=True, max_length=200, verbose_name='referencia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.product', verbose_name='producto')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'movimiento de stock',
                'verbose_name_plural': 'movimientos de stock',
                'ordering': ['-created_at'],
            },
        ),
    ]
