# Generated by Django 5.2.17 on 2026-08-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promo_active',
            field=models.BooleanField(default=False, verbose_name='promo activa'),
        ),
        migrations.AddField(
            model_name='product',
            name='promo_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio promocional (se usa si promo activa; no se acumula con happy hour).', max_digits=10, null=True, verbose_name='precio promo'),
        ),
    ]
