# Generated by Django 5.2.17 on 2026-08-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_promo_active_product_promo_price'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('promo_active', False), models.Q(('promo_price__gt', 0), ('promo_price__isnull', False)), _connector='OR'), name='promo_active_requires_price'),
        ),
    ]
