# Generated by Django 5.2.17 on 2026-08-26 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_promo_active_requires_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_composed',
            field=models.BooleanField(default=False, help_text='Si está activo, al vender se descuenta la materia prima (RecipeItem).', verbose_name='elaborado (con receta)'),
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Cantidad de ingrediente necesaria por 1 unidad del producto.', max_digits=10, verbose_name='cantidad por unidad')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_recipes', to='inventory.product', verbose_name='ingrediente')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='inventory.product', verbose_name='producto elaborado')),
            ],
            options={
                'verbose_name': 'ingrediente de receta',
                'verbose_name_plural': 'ingredientes de receta',
                'unique_together': {('product', 'ingredient')},
            },
        ),
    ]
