# Generated by Django 5.2.17 on 2026-08-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_product_is_composed_recipeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_raw_material',
            field=models.BooleanField(default=False, help_text='Marca el producto como materia prima (se lista en Materiales).', verbose_name='materia prima'),
        ),
    ]
