# Generated by Django 5.2.17 on 2026-08-26 15:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('dni', models.CharField(blank=True, max_length=20, verbose_name='DNI')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='puntos de fidelización')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_per_currency', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=10, verbose_name='puntos por moneda')),
                ('points_required_for_discount', models.PositiveIntegerField(default=100, verbose_name='puntos para descuento')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=10, verbose_name='monto del descuento')),
            ],
            options={
                'verbose_name': 'configuración de fidelización',
                'verbose_name_plural': 'configuración de fidelización',
            },
        ),
    ]
