# Generated by Django 5.2.17 on 2026-08-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltyconfig',
            name='max_discount_percent',
            field=models.PositiveIntegerField(default=50, help_text='Tope del descuento manual sobre el subtotal (0-100).', verbose_name='descuento manual máximo (%)'),
        ),
    ]
