# Generated by Django 5.2.17 on 2026-08-26 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_loyaltyconfig_max_discount_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltyconfig',
            name='max_discount_percent',
            field=models.PositiveIntegerField(default=50, help_text='Tope del descuento manual sobre el subtotal (0-100).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='descuento manual máximo (%)'),
        ),
    ]
