# Generated by Django 5.2.17 on 2026-08-26 15:42

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0001_initial'),
        ('tables', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='apertura')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='cierre')),
                ('opening_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='monto de apertura')),
                ('closing_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='monto de cierre')),
                ('expected_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='monto esperado')),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='monto real')),
                ('status', models.CharField(choices=[('abierta', 'abierta'), ('cerrada', 'cerrada')], default='abierta', max_length=20, verbose_name='estado')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_registers', to=settings.AUTH_USER_MODEL, verbose_name='abierta por')),
            ],
            options={
                'verbose_name': 'caja registradora',
                'verbose_name_plural': 'cajas registradoras',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='número de ticket')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='subtotal')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='descuento')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='total')),
                ('payment_method', models.CharField(choices=[('efectivo', 'efectivo'), ('tarjeta', 'tarjeta'), ('transferencia', 'transferencia'), ('otro', 'otro')], default='efectivo', max_length=20, verbose_name='método de pago')),
                ('cash_received', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='efectivo recibido')),
                ('change', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='vuelto')),
                ('status', models.CharField(choices=[('completada', 'completada'), ('anulada', 'anulada')], default='completada', max_length=20, verbose_name='estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True, verbose_name='anulada el')),
                ('void_reason', models.CharField(blank=True, max_length=250, verbose_name='motivo de anulación')),
                ('cash_register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='sales.cashregister', verbose_name='caja')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='customers.customer', verbose_name='cliente')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='tables.table', verbose_name='mesa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='vendedor')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voided_sales', to=settings.AUTH_USER_MODEL, verbose_name='anulada por')),
            ],
            options={
                'verbose_name': 'venta',
                'verbose_name_plural': 'ventas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='subtotal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='inventory.product', verbose_name='producto')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale', verbose_name='venta')),
            ],
            options={
                'verbose_name': 'ítem de venta',
                'verbose_name_plural': 'ítems de venta',
            },
        ),
    ]
