# Generated by Django 5.2.17 on 2026-08-26 16:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HappyHourConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='habilitado')),
                ('start_time', models.TimeField(verbose_name='inicio')),
                ('end_time', models.TimeField(verbose_name='fin')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('15'), max_digits=5, verbose_name='descuento (%)')),
                ('name', models.CharField(default='Happy hour', max_length=100, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'configuración de happy hour',
                'verbose_name_plural': 'configuración de happy hour',
            },
        ),
        migrations.AddField(
            model_name='cashregister',
            name='counted_card',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='contado tarjeta'),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='counted_cash',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='contado efectivo'),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='counted_other',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='contado otros'),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='counted_transfer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='contado transferencia'),
        ),
        migrations.AddField(
            model_name='sale',
            name='tip',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='propina'),
        ),
    ]
