# Generated by Django 5.2.17 on 2026-08-26 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_happyhourconfig_cashregister_counted_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='happyhourconfig',
            name='end_time',
            field=models.TimeField(default=datetime.time(21, 0), verbose_name='fin'),
        ),
        migrations.AlterField(
            model_name='happyhourconfig',
            name='start_time',
            field=models.TimeField(default=datetime.time(18, 0), verbose_name='inicio'),
        ),
    ]
