# Generated by Django 5.2.17 on 2026-08-26 16:30

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_happyhourconfig_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='happyhourconfig',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('15'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='descuento (%)'),
        ),
    ]
