# Generated by Django 5.2.17 on 2026-08-26 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_happyhourconfig_discount_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_print_ticket', models.BooleanField(default=True, verbose_name='imprimir ticket en POS')),
            ],
            options={
                'verbose_name': 'configuración de ventas',
                'verbose_name_plural': 'configuración de ventas',
            },
        ),
    ]
